routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::group(['middleware' => ['auth'], 'as' => 'client.', 'prefix' => '/client'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/send-request', 'RequestController@sendRequest')->name('send.request');
    Route::post('/mark-as-read/{id}', 'RequestController@markAsReadById')->name('mark.as.read');
});

resources/views/partials/contact-form.blade.php
@error('upload')
    <div class="form-group row">
        <div class="col">
            <span class="invalid-feedback d-block" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        </div>
    </div>
@enderror
<form method="POST" action="{{ route('client.send.request') }}" enctype="multipart/form-data">
    @csrf
    <div class="form-group row">
        <label for="subject" class="col-md-4 col-form-label text-md-right">{{ __('layout.subject') }}</label>
        <div class="col-md-6">
            <input id="subject" type="text" class="form-control @error('subject') is-invalid @enderror" name="subject" value="{{ old('subject') }}" required autocomplete="subject" autofocus maxlength="100">
            @error('subject')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="message" class="col-md-4 col-form-label text-md-right">{{ __('layout.message') }}</label>
        <div class="col-md-6">
            <textarea id="message" type="text" class="form-control @error('message') is-invalid @enderror" name="message" required maxlength="1000"> {{ old('message') }}</textarea>
            @error('message')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="file" class="col-md-4 col-form-label text-md-right">{{ __('layout.add-file') }}</label>
        <div class="col-md-6">
            <input id="file" type="file" class="form-control border-0 @error('file') is-invalid @enderror" name="file">
            @error('file')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-8 offset-md-4">
            <button type="submit" class="btn btn-primary">
                {{ __('layout.send') }}
            </button>
        </div>
    </div>
</form>

resources/views/partials/users-requests-list.blade.php
@if(!empty($list))
    <div class="col list-wrapper">
        <div class="card">
            <div class="card-header">
                {{ __('layout.contact-form') }}
            </div>
            <div class="card-body">
                <hr>
                @foreach($list as $item)
                    <?php /** @var \App\Models\UserRequest $item */ ?>
                    <div class="form-group row">
                        <div class="col-1">
                            {{ $item->id }}
                        </div>
                        <div class="col-1">
                            {{ $item->user->name }}
                        </div>
                        <div class="col">
                            {{ $item->user->email }}
                        </div>
                        <div class="col">
                            {{ $item->subject }}
                        </div>
                        <div class="col message-container">
                            {{ $item->message }}
                        </div>
                        <div class="col-1">
                            <a href="{{ $item->file_path }}" target="_blank">
                                file
                            </a>
                        </div>
                        @if($item->is_answered)
                            <div class="col green">
                                {{ __('layout.answered') }}
                            </div>
                        @else
                            <div class="col">
                                <form method="POST" action="{{ route('client.mark.as.read', ['id' => $item->id]) }}">
                                    @csrf
                                    <button type="submit" class="btn btn-danger">
                                        {{ __('layout.mark-as-answered') }}
                                    </button>
                                </form>
                            </div>
                        @endif
                    </div>
                    <hr>
                @endforeach
                {{ $list->links() }}
            </div>
        </div>
    </div>
@endif